config/routes.rb
Rails.application.routes.draw do
  

  get "/sunstars/new" => "sunstars#new", as: :new_sunstars
  post "/sunstars" => "sunstars#create", as: :sunstars
  get '/sunstars/note' => 'sunstars#note', as: :note_sunstar
  get "/sunstars/:id" => "sunstars#show", as: :sunstar
  get "/sunstars" => "sunstars#index"
  get "/sunstars/:id/edit" => "sunstars#edit", as: :edit_sunstar
  patch "/sunstars/:id/" => "sunstars#update"
  delete "/sunstars/:id" => "sunstars#destroy"
  root "sunstars#index"

end

app/models/sunstar.rb
class Sunstar < ActiveRecord::Base

validates :name, presence: true, uniqueness: true
validates :email, presence: true, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
validates :message, presence: true 


  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sunstars_controller.rb
class SunstarsController < ApplicationController
  def index
      @sunstars = Sunstar.all
    end

    def new
      @sunstar = Sunstar.new 
    end

    def create 
      @sunstar = Sunstar.new sunstar_params
     if @sunstar.save
        redirect_to sunstars_path
      else
        render :new
      end
    end
    def edit
      @sunstar = Sunstar.find params[:id]
    end
    def update
    @sunstar = Sunstar.find params[:id]
   # sunstars_params = params.require(:sunstars).permit(:person, :text)
  if @sunstar.update sunstar_params
    redirect_to sunstars_path
    else
    render :edit
  end
end

  def destroy
    @sunstar = Sunstar.find params[:id]
    @sunstar.destroy
    redirect_to sunstars_path
    
  end
    private

    def sunstar_params
      params.require(:sunstar).permit(:email, :message, :name, :department)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sunstars_helper.rb
module SunstarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Worktest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href="/sunstars/new">Add a new</a>
  <a href="/sunstars">Edit your Request</a>
  <a href="/sunstars/note">Add a note to your request</a>
<%= yield %>

</body>
</html>

app/views/sunstars/_form.html.erb
<% if @sunstar.errors.any? %>
  <ul>
    <% @sunstar.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @sunstar do |f| %>

    <%= f.label "Name" %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <hr>
    <br>
    <%= f.radio_button(:department, 'Sales', :checked => true) %>
    <%= f.label(:salesdep, "Sales") %>
    <%= f.radio_button(:department, 'Marketing') %>
    <%= f.label(:marketingdep, "Marketing") %>
    <%= f.radio_button(:department, 'Technical') %>
    <%= f.label(:technicaldep, "Technical") %>



    <%= f.label :message %> <br>
    <%= f.text_area :message %>
    <br>

    <br>
    <%= f.submit %>
    <% f.button "Save", type: :save %>
    
    <% end %>

app/views/sunstars/edit.html.erb
<h1>If any changes, please up date request.</h1>

<% if @sunstar.errors.any? %>
  <ul>
    <% @sunstar.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @sunstar do |f| %>

    <%= f.label "Name" %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>

    <%= f.label :message %> <br>
    <%= f.text_area :message %>
    <br>

    <br>
    <%= f.submit %>
    <% f.button "Update", type: :update %>
    
    <% end %>

app/views/sunstars/index.html.erb
<h1>Please edit and delete your support requests</h1>



<% @sunstars.each do |sunstar| %>
    <h3><%= link_to sunstar.name, sunstars_path %></h3>
    
    <p>Name: <%= sunstar.name %></p>
    <p>Email: <%= sunstar.email %></p>
    <p>Department: <%= sunstar.department %></p>
    <p>message: <%= sunstar.message %></p>
    
    <%= link_to "Edit", edit_sunstar_path(sunstar)  %>
    <%= link_to "delete", sunstar_path(sunstar), method:
    :delete, data: {confirm: "Thank you for removing you request?"} %>

    <% end %>

app/views/sunstars/new.html.erb
<h1>Please add your request</h1>



<%= render "form" %>

app/views/sunstars/note.html.erb
<h1>Please tag a note</h1>

app/views/sunstars/show.html.erb
<h1>Locate your request to edit</h1>


    <% @sunstars.each do |sunstar| %>
    <h3><%= link_to sunstar.name, sunstars_path %></h3>
    
    <p>Name: <%= sunstar.name %></p>
    <p>Email: <%= sunstar.email %></p>
    <p>message: <%= sunstar.message %></p>
    
    <%= link_to "Edit", edit_sunstar_path(sunstar)  %>

    <% end %>